# Generated by Django 3.2.3 on 2021-05-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='classroom',
        ),
    ]
