# Generated by Django 3.2.3 on 2021-05-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_rename_name_classroom_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom',
            new_name='classroomName',
        ),
        migrations.AlterField(
            model_name='classnotes',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='classroom.classroom'),
        ),
    ]
